# Generated by Django 4.1.7 on 2023-04-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tripInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('length', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('picture', models.CharField(max_length=30)),
            ],
        ),
    ]
